name: "Setup and run go tests"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
          with:
            go-version: '1.20'
      - name: run tests
        run: go test -v ./...
